/**
 * Script simples para executar o AutoGeneratorDDD
 */

async function main() {
  console.log('🎯 Executando AutoGeneratorDDD');
  console.log('================================\n');

  console.log('📋 Configurações:');
  console.log('  • Modules Path: examples');
  console.log('  • Domain Path: src/domain');
  console.log('  • Bounded Context: user-example');
  console.log('  • Verbose: true');
  console.log('  • Force: false');
  console.log('  • Dry Run: true (mude para false para gerar arquivos reais)\n');

  try {
    // Importar dinamicamente
    const { autoGenerateDDDFromZodSchemas } = await import('../src/auto-generator-ddd.js');

    await autoGenerateDDDFromZodSchemas({
      modulesPath: 'examples',
      domainPath: 'src/domain',
      boundedContext: 'user-example',
      verbose: true,
      force: true,
      dryRun: true // ⚠️ MUDE PARA false PARA GERAR ARQUIVOS REAIS
    });

    console.log('\n✅ Geração DDD concluída com sucesso!');
    console.log('\n📁 Verifique os arquivos gerados em:');
    console.log('  • examples/user-example/');
    console.log('  • src/domain/user-example/');

    console.log('\n💡 Para gerar arquivos reais, mude dryRun: true para false');

  } catch (error) {
    console.error('\n❌ Erro na geração DDD:', error);
    console.error('Stack:', error.stack);
  }
}

// Executar
main().catch(console.error);
